// frontend/src/components/common/Footer.tsx
import React from 'react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-gray-800 text-white mt-auto">
      <div className="container mx-auto px-4 py-6">
        <div className="text-center">
          <p className="text-sm">
            &copy; {new Date().getFullYear()} PizzaOrders. All rights reserved.
          </p>
          <p className="text-xs text-gray-400 mt-2">
            A pet project for learning Clean Architecture
          </p>
        </div>
      </div>
    </footer>
  );
};

// pizza-orders-client/src/components/footer/footer.component.ts

import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FooterComponent {
  currentYear = new Date().getFullYear();
}

<footer class="bg-gray-900 text-gray-300">
  <div class="container mx-auto px-4 sm:px-6 lg:px-8 py-4 text-center">
    <p>&copy; {{ currentYear }} PizzaOrders. All rights reserved.</p>
  </div>
</footer>
