// frontend/src/components/common/Header.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { useCart } from '../../hooks/useCart';

export const Header: React.FC = () => {
  const { isAuthenticated, isAdmin, user, logout } = useAuth();
  const { cart } = useCart();

  const itemCount = cart?.items.reduce((sum, item) => sum + item.quantity, 0) || 0;

  return (
    <header className="bg-blue-600 text-white shadow-md">
      <div className="container mx-auto px-4 py-4">
        <div className="flex items-center justify-between">
          <Link to="/" className="text-2xl font-bold">
            PizzaOrders
          </Link>

          <nav className="flex items-center gap-6">
            <Link to="/" className="hover:text-blue-200">
              Products
            </Link>
            <Link to="/cart" className="hover:text-blue-200 relative">
              Cart
              {itemCount > 0 && (
                <span className="absolute -top-2 -right-3 bg-red-500 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">
                  {itemCount}
                </span>
              )}
            </Link>

            {isAdmin && (
              <Link to="/admin" className="hover:text-blue-200 font-semibold">
                Admin Panel
              </Link>
            )}

            {isAuthenticated ? (
              <div className="flex items-center gap-4">
                <span className="text-sm">{user?.email}</span>
                <button
                  onClick={logout}
                  className="bg-red-500 hover:bg-red-600 px-4 py-2 rounded"
                >
                  Logout
                </button>
              </div>
            ) : (
              <div className="flex items-center gap-4">
                <Link to="/login" className="hover:text-blue-200">
                  Login
                </Link>
                <Link
                  to="/register"
                  className="bg-green-500 hover:bg-green-600 px-4 py-2 rounded"
                >
                  Register
                </Link>
              </div>
            )}
          </nav>
        </div>
      </div>
    </header>
  );
};

// angular-client/src/components/header/header.component.ts
import { Component, ChangeDetectionStrategy, output, inject, signal } from '@angular/core';
import { CartService } from '../../services/cart.service';
import { AuthService } from '../../services/auth.service';
import { LoginModalComponent } from '../login-modal/login-modal.component';
import { SignupModalComponent } from '../signup-modal/signup-modal.component';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LoginModalComponent, SignupModalComponent]
})
export class HeaderComponent {
  cartClick = output<void>();
  adminPanelClick = output<void>();
  authSuccess = output<string>();

  cartService = inject(CartService);
  authService = inject(AuthService);
  
  totalItems = this.cartService.totalItems;
  currentUser = this.authService.currentUser;
  isAdmin = this.authService.isAdmin;

  isLoginModalVisible = signal(false);
  isSignupModalVisible = signal(false);

  onCartClick() {
    this.cartClick.emit();
  }

  logout() {
    this.authService.logout();
    this.authSuccess.emit('You have been successfully logged out.');
  }

  handleLoginSuccess() {
    this.isLoginModalVisible.set(false);
    this.authSuccess.emit(`Welcome back, ${this.currentUser()?.name}!`);
  }
  
  handleSignupSuccess() {
    this.isSignupModalVisible.set(false);
    this.authSuccess.emit(`Welcome, ${this.currentUser()?.name}! Your account is ready.`);
  }
}

<header class="bg-white shadow-md sticky top-0 z-40">
  <div class="container mx-auto px-4 py-3 flex justify-between items-center">
    <div class="flex items-center space-x-2">
      <i class="fas fa-pizza-slice text-3xl text-red-600"></i>
      <h1 class="text-2xl font-bold text-gray-800">Pizza Orders</h1>
    </div>
    <div class="flex items-center space-x-6">
      <div class="hidden md:flex items-center space-x-4">
        @if (currentUser()) {
          @if (isAdmin()) {
            <button (click)="adminPanelClick.emit()" class="text-gray-600 hover:text-red-600 font-medium transition-colors duration-200">
              <i class="fas fa-user-shield mr-2"></i>Admin Panel
            </button>
          }
          <button (click)="logout()" class="bg-gray-600 text-white font-bold py-2 px-4 rounded-full hover:bg-gray-700 transition-colors duration-300 shadow-md text-sm">Logout</button>
        } @else {
          <button (click)="isLoginModalVisible.set(true)" class="text-gray-600 hover:text-red-600 font-medium transition-colors duration-200">Login</button>
          <button (click)="isSignupModalVisible.set(true)" class="bg-red-600 text-white font-bold py-2 px-4 rounded-full hover:bg-red-700 transition-colors duration-300 shadow-md text-sm">Sign Up</button>
        }
      </div>
      <button (click)="onCartClick()" class="relative text-gray-600 hover:text-red-600 transition-colors duration-200">
        <i class="fas fa-shopping-cart text-2xl"></i>
        @if (totalItems() > 0) {
          <span class="absolute -top-2 -right-2 bg-red-600 text-white text-xs font-bold rounded-full h-5 w-5 flex items-center justify-center">
            {{ totalItems() }}
          </span>
        }
      </button>
    </div>
  </div>
</header>

<app-login-modal
  [isVisible]="isLoginModalVisible()"
  (closeModal)="isLoginModalVisible.set(false)"
  (loginSuccess)="handleLoginSuccess()">
</app-login-modal>

<app-signup-modal
  [isVisible]="isSignupModalVisible()"
  (closeModal)="isSignupModalVisible.set(false)"
  (signupSuccess)="handleSignupSuccess()">
</app-signup-modal>
