// frontend/src/components/products/ProductCard.tsx
import React, { useState } from 'react';
import type { Product } from '../../types';

interface ProductCardProps {
  product: Product;
  onAddToCart: (productId: number, quantity: number, toppingIds: number[]) => void;
}

export const ProductCard: React.FC<ProductCardProps> = ({ product, onAddToCart }) => {
  const [quantity, setQuantity] = useState(1);
  const [loading, setLoading] = useState(false);

  const handleAddToCart = async () => {
    setLoading(true);
    try {
      await onAddToCart(product.id, quantity, []);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-lg shadow-md p-4 hover:shadow-lg transition-shadow">
      {product.imageUrl && (
        <img
          src={product.imageUrl}
          alt={product.name}
          className="w-full h-48 object-cover rounded-md mb-4"
        />
      )}
      <h3 className="text-xl font-bold mb-2">{product.name}</h3>
      {product.description && <p className="text-gray-600 mb-3">{product.description}</p>}
      <div className="flex items-center justify-between mb-4">
        <span className="text-2xl font-bold text-blue-600">${product.basePrice.toFixed(2)}</span>
        {product.hasToppings && (
          <span className="text-sm text-green-600">Customizable</span>
        )}
      </div>
      <div className="flex items-center gap-2">
        <input
          type="number"
          min="1"
          value={quantity}
          onChange={(e) => setQuantity(Math.max(1, parseInt(e.target.value) || 1))}
          className="border rounded px-2 py-1 w-16 text-center"
        />
        <button
          onClick={handleAddToCart}
          disabled={loading}
          className="flex-1 bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded disabled:opacity-50"
        >
          {loading ? 'Adding...' : 'Add to Cart'}
        </button>
      </div>
    </div>
  );
};

// angular-client/src/components/product-card/product-card.component.ts
import { Component, ChangeDetectionStrategy, input, output } from '@angular/core';
import { Product, ProductType } from '../../models/product.model';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgOptimizedImage]
})
export class ProductCardComponent {
  product = input.required<Product>();
  selectProduct = output<Product>();

  productTypes = ProductType;

  onSelectProduct() {
    this.selectProduct.emit(this.product());
  }
}

<div class="bg-white rounded-lg shadow-lg overflow-hidden transform hover:-translate-y-2 transition-transform duration-300 flex flex-col h-full">
  <img [ngSrc]="product().imageUrl" [alt]="product().name" width="400" height="250" class="w-full h-48 object-cover">
  <div class="p-5 flex flex-col flex-grow">
    <h3 class="text-xl font-bold text-gray-900">{{ product().name }}</h3>
    <p class="text-gray-600 mt-2 flex-grow">{{ product().description }}</p>
    <div class="mt-4 flex justify-between items-center">
      <span class="text-2xl font-bold text-red-600">${{ product().price.toFixed(2) }}</span>
      <button (click)="onSelectProduct()" class="bg-red-600 text-white font-bold py-2 px-4 rounded-full hover:bg-red-700 transition-colors duration-300 shadow-md">
        @if (product().productType === productTypes.Pizza) {
          <span>Customize</span>
        } @else {
          <span>Add to Cart</span>
        }
      </button>
    </div>
  </div>
</div>
