// pizza-orders-client/components/Header.tsx
import React, { useState } from 'react';
import { NavLink, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import { PizzaIcon, ShoppingCartIcon, UserCircleIcon, MenuIcon, XIcon, LogoutIcon } from './Icons';

const Header: React.FC = () => {
  const { user, logout } = useAuth();
  const { cartCount } = useCart();
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [isProfileOpen, setIsProfileOpen] = useState(false);

  const navLinkClass = ({ isActive }: { isActive: boolean }) =>
    `px-3 py-2 rounded-md text-sm font-medium transition-colors ${
      isActive ? 'bg-primary text-white' : 'text-gray-300 hover:bg-secondary-light hover:text-white'
    }`;

  const mobileNavLinkClass = ({ isActive }: { isActive: boolean }) =>
    `block px-3 py-2 rounded-md text-base font-medium transition-colors ${
      isActive ? 'bg-primary text-white' : 'text-gray-300 hover:bg-secondary-light hover:text-white'
    }`;
    
  return (
    <nav className="bg-secondary shadow-lg sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center">
            <Link to="/" className="flex-shrink-0 flex items-center text-white">
              <PizzaIcon className="h-8 w-8 text-primary" />
              <span className="ml-2 text-xl font-bold">PizzaOrders</span>
            </Link>
            <div className="hidden md:block">
              <div className="ml-10 flex items-baseline space-x-4">
                <NavLink to="/" className={navLinkClass}>Home</NavLink>
                <NavLink to="/menu" className={navLinkClass}>Menu</NavLink>
                <NavLink to="/constructor" className={navLinkClass}>Pizza Builder</NavLink>
                <NavLink to="/contact" className={navLinkClass}>Contact</NavLink>
                {user && <NavLink to="/orders" className={navLinkClass}>My Orders</NavLink>}
                {user?.role === 'admin' && <NavLink to="/admin" className={navLinkClass}>Admin</NavLink>}
              </div>
            </div>
          </div>
          <div className="hidden md:block">
            <div className="ml-4 flex items-center md:ml-6 space-x-4">
              <Link to="/checkout" className="relative p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-secondary focus:ring-white">
                <ShoppingCartIcon className="h-6 w-6" />
                {cartCount > 0 && (
                  <span className="absolute -top-2 -right-2 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-white transform translate-x-1/2 -translate-y-1/2 bg-accent rounded-full">
                    {cartCount}
                  </span>
                )}
              </Link>
              {user ? (
                <div className="ml-3 relative">
                  <div>
                    <button onClick={() => setIsProfileOpen(!isProfileOpen)} className="max-w-xs bg-secondary rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-secondary focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                      <span className="sr-only">Open user menu</span>
                      <UserCircleIcon className="h-8 w-8 text-gray-400"/>
                    </button>
                  </div>
                  {isProfileOpen && (
                    <div className="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button">
                      <div className="px-4 py-2 text-sm text-gray-700 border-b">{user.name}</div>
                      <a href="#" onClick={(e) => { e.preventDefault(); logout(); setIsProfileOpen(false); }} className="flex items-center w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100" role="menuitem">
                        <LogoutIcon className="h-4 w-4 mr-2" />
                        Sign out
                      </a>
                    </div>
                  )}
                </div>
              ) : (
                <NavLink to="/auth" className={navLinkClass}>Login</NavLink>
              )}
            </div>
          </div>
          <div className="-mr-2 flex md:hidden">
            <Link to="/checkout" className="relative p-1 mr-2 rounded-full text-gray-400 hover:text-white focus:outline-none">
              <ShoppingCartIcon className="h-6 w-6" />
              {cartCount > 0 && (
                <span className="absolute -top-2 -right-2 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-white transform translate-x-1/2 -translate-y-1/2 bg-accent rounded-full">{cartCount}</span>
              )}
            </Link>
            <button onClick={() => setIsMenuOpen(!isMenuOpen)} type="button" className="bg-secondary-light inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-secondary focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-secondary focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
              <span className="sr-only">Open main menu</span>
              {isMenuOpen ? <XIcon className="block h-6 w-6" /> : <MenuIcon className="block h-6 w-6" />}
            </button>
          </div>
        </div>
      </div>

      {isMenuOpen && (
        <div className="md:hidden" id="mobile-menu">
          <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3">
            <NavLink to="/" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>Home</NavLink>
            <NavLink to="/menu" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>Menu</NavLink>
            <NavLink to="/constructor" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>Pizza Builder</NavLink>
            <NavLink to="/contact" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>Contact</NavLink>
            {user && <NavLink to="/orders" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>My Orders</NavLink>}
            {user?.role === 'admin' && <NavLink to="/admin" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>Admin Panel</NavLink>}
             {user ? (
                <div className="pt-4 pb-3 border-t border-secondary-light">
                    <div className="flex items-center px-5">
                      <UserCircleIcon className="h-10 w-10 text-gray-400"/>
                      <div className="ml-3">
                        <div className="text-base font-medium leading-none text-white">{user.name}</div>
                        <div className="text-sm font-medium leading-none text-gray-400">{user.email}</div>
                      </div>
                    </div>
                    <div className="mt-3 px-2 space-y-1">
                      <a href="#" onClick={(e) => { e.preventDefault(); logout(); setIsMenuOpen(false); }} className="flex items-center w-full text-left px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-secondary-light">
                        <LogoutIcon className="h-5 w-5 mr-2" />
                        Sign out
                      </a>
                    </div>
                </div>
              ) : (
                <NavLink to="/auth" className={mobileNavLinkClass} onClick={() => setIsMenuOpen(false)}>Login</NavLink>
              )}
          </div>
        </div>
      )}
    </nav>
  );
};

export default Header;

// pizza-orders-client/src/components/header/header.component.ts

import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import {RouterLink, RouterLinkActive} from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CartService } from '../../services/cart.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [CommonModule, RouterLink, RouterLinkActive]
})
export class HeaderComponent {
  authService = inject(AuthService);
  cartService = inject(CartService);
  isMobileMenuOpen = false;

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  logout() {
    this.authService.logout();
  }
}

<header class="bg-white shadow-md sticky top-0 z-50">
  <nav class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <a routerLink="/home" class="flex-shrink-0 text-2xl font-bold text-orange-600">
          Pizza Planet
        </a>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <a routerLink="/home" routerLinkActive="text-orange-600" [routerLinkActiveOptions]="{exact: true}" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Home</a>
            <a routerLink="/menu" routerLinkActive="text-orange-600" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Menu</a>
            <a routerLink="/build-your-own" routerLinkActive="text-orange-600" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Build Your Own</a>
            <a routerLink="/contact" routerLinkActive="text-orange-600" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Contact</a>
          </div>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <a routerLink="/cart" class="relative mr-4 text-gray-600 hover:text-orange-600">
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c.51 0 .962-.328 1.093-.828l2.91-6.616c.203-.461-.133-1.002-.642-1.002H5.316" />
            </svg>
            @if (cartService.itemCount() > 0) {
              <span class="absolute -top-2 -right-2 bg-orange-600 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">{{ cartService.itemCount() }}</span>
            }
          </a>

          @if (authService.isLoggedIn()) {
            @if (authService.isAdmin()) {
               <a routerLink="/admin" class="text-sm font-medium text-gray-700 hover:text-orange-600 mr-4">Admin</a>
            }
            <a routerLink="/order-history" class="text-sm font-medium text-gray-700 hover:text-orange-600 mr-4">My Orders</a>
            <button (click)="logout()" class="text-sm font-medium text-gray-700 hover:text-orange-600">Logout</button>
          } @else {
            <a routerLink="/login" class="text-sm font-medium text-gray-700 hover:text-orange-600 mr-4">Sign In</a>
            <a routerLink="/register" class="bg-orange-600 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-orange-700">Register</a>
          }
        </div>
      </div>
      <div class="-mr-2 flex md:hidden">
        <button (click)="toggleMobileMenu()" type="button" class="bg-gray-100 inline-flex items-center justify-center p-2 rounded-md text-gray-600 hover:text-orange-600 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-orange-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg [class]="{'hidden': isMobileMenuOpen, 'block': !isMobileMenuOpen }" class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg [class]="{'hidden': !isMobileMenuOpen, 'block': isMobileMenuOpen }" class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </nav>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div [class]="{'block': isMobileMenuOpen, 'hidden': !isMobileMenuOpen}" class="md:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
      <a routerLink="/home" routerLinkActive="bg-orange-100 text-orange-700" [routerLinkActiveOptions]="{exact: true}" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Home</a>
      <a routerLink="/menu" routerLinkActive="bg-orange-100 text-orange-700" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Menu</a>
      <a routerLink="/build-your-own" routerLinkActive="bg-orange-100 text-orange-700" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Build Your Own</a>
      <a routerLink="/contact" routerLinkActive="bg-orange-100 text-orange-700" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Contact</a>
    </div>
    <div class="pt-4 pb-3 border-t border-gray-200">
        <div class="flex items-center px-5">
            <a routerLink="/cart" class="relative mr-4 text-gray-600 hover:text-orange-600">
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c.51 0 .962-.328 1.093-.828l2.91-6.616c.203-.461-.133-1.002-.642-1.002H5.316" />
                </svg>
                @if (cartService.itemCount() > 0) {
                  <span class="absolute -top-2 -right-2 bg-orange-600 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">{{ cartService.itemCount() }}</span>
                }
            </a>
        </div>
      <div class="mt-3 px-2 space-y-1">
        @if (authService.isLoggedIn()) {
            @if(authService.isAdmin()){
              <a routerLink="/admin" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Admin</a>
            }
            <a routerLink="/order-history" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">My Orders</a>
            <a (click)="logout()" href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Logout</a>
        } @else {
            <a routerLink="/login" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Sign In</a>
            <a routerLink="/register" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Register</a>
        }
      </div>
    </div>
  </div>
</header>
