// pizza-orders-client/src/components/header/header.component.ts

import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import {RouterLink, RouterLinkActive} from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { CartService } from '../../services/cart.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
    imports: [CommonModule, RouterLink, RouterLinkActive]
})
export class HeaderComponent {
  authService = inject(AuthService);
  cartService = inject(CartService);
  isMobileMenuOpen = false;

  toggleMobileMenu() {
    this.isMobileMenuOpen = !this.isMobileMenuOpen;
  }

  logout() {
    this.authService.logout();
  }
}

<header class="bg-white shadow-md sticky top-0 z-50">
  <nav class="container mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <a routerLink="/home" class="flex-shrink-0 text-2xl font-bold text-orange-600">
          Pizza Planet
        </a>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <a routerLink="/home" routerLinkActive="text-orange-600" [routerLinkActiveOptions]="{exact: true}" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Home</a>
            <a routerLink="/menu" routerLinkActive="text-orange-600" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Menu</a>
            <a routerLink="/build-your-own" routerLinkActive="text-orange-600" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Build Your Own</a>
            <a routerLink="/contact" routerLinkActive="text-orange-600" class="text-gray-700 hover:text-orange-600 px-3 py-2 rounded-md text-sm font-medium">Contact</a>
          </div>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <a routerLink="/cart" class="relative mr-4 text-gray-600 hover:text-orange-600">
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c.51 0 .962-.328 1.093-.828l2.91-6.616c.203-.461-.133-1.002-.642-1.002H5.316" />
            </svg>
            @if (cartService.itemCount() > 0) {
              <span class="absolute -top-2 -right-2 bg-orange-600 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">{{ cartService.itemCount() }}</span>
            }
          </a>

          @if (authService.isLoggedIn()) {
            @if (authService.isAdmin()) {
               <a routerLink="/admin" class="text-sm font-medium text-gray-700 hover:text-orange-600 mr-4">Admin</a>
            }
            <a routerLink="/order-history" class="text-sm font-medium text-gray-700 hover:text-orange-600 mr-4">My Orders</a>
            <button (click)="logout()" class="text-sm font-medium text-gray-700 hover:text-orange-600">Logout</button>
          } @else {
            <a routerLink="/login" class="text-sm font-medium text-gray-700 hover:text-orange-600 mr-4">Sign In</a>
            <a routerLink="/register" class="bg-orange-600 text-white px-3 py-2 rounded-md text-sm font-medium hover:bg-orange-700">Register</a>
          }
        </div>
      </div>
      <div class="-mr-2 flex md:hidden">
        <button (click)="toggleMobileMenu()" type="button" class="bg-gray-100 inline-flex items-center justify-center p-2 rounded-md text-gray-600 hover:text-orange-600 hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-orange-500" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg [class]="{'hidden': isMobileMenuOpen, 'block': !isMobileMenuOpen }" class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg [class]="{'hidden': !isMobileMenuOpen, 'block': isMobileMenuOpen }" class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </nav>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div [class]="{'block': isMobileMenuOpen, 'hidden': !isMobileMenuOpen}" class="md:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
      <a routerLink="/home" routerLinkActive="bg-orange-100 text-orange-700" [routerLinkActiveOptions]="{exact: true}" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Home</a>
      <a routerLink="/menu" routerLinkActive="bg-orange-100 text-orange-700" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Menu</a>
      <a routerLink="/build-your-own" routerLinkActive="bg-orange-100 text-orange-700" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Build Your Own</a>
      <a routerLink="/contact" routerLinkActive="bg-orange-100 text-orange-700" class="text-gray-700 hover:text-orange-600 block px-3 py-2 rounded-md text-base font-medium">Contact</a>
    </div>
    <div class="pt-4 pb-3 border-t border-gray-200">
        <div class="flex items-center px-5">
            <a routerLink="/cart" class="relative mr-4 text-gray-600 hover:text-orange-600">
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c.51 0 .962-.328 1.093-.828l2.91-6.616c.203-.461-.133-1.002-.642-1.002H5.316" />
                </svg>
                @if (cartService.itemCount() > 0) {
                  <span class="absolute -top-2 -right-2 bg-orange-600 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">{{ cartService.itemCount() }}</span>
                }
            </a>
        </div>
      <div class="mt-3 px-2 space-y-1">
        @if (authService.isLoggedIn()) {
            @if(authService.isAdmin()){
              <a routerLink="/admin" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Admin</a>
            }
            <a routerLink="/order-history" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">My Orders</a>
            <a (click)="logout()" href="#" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Logout</a>
        } @else {
            <a routerLink="/login" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Sign In</a>
            <a routerLink="/register" class="block rounded-md px-3 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800">Register</a>
        }
      </div>
    </div>
  </div>
</header>

// frontend/src/components/common/Header.tsx
import React, { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../../hooks/useAuth';
import { useReduxCart } from '../../hooks/useReduxCart';
import { AuthModal } from './AuthModal';
import { ProductType } from '../../types';

interface HeaderProps {
  selectedType?: ProductType;
  onTypeChange?: (type: ProductType) => void;
}

export const Header: React.FC<HeaderProps> = ({ selectedType, onTypeChange }) => {
  const { isAuthenticated, isAdmin, user, logout } = useAuth();
  const { cart, openCart } = useReduxCart();
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const location = useLocation();

  const itemCount = cart?.items.reduce((sum, item) => sum + item.quantity, 0) || 0;

  const isMenuPage = location.pathname === '/';

  const categories = [
    { type: ProductType.Pizza, label: 'Pizza', icon: null },
    { type: ProductType.Drink, label: 'Drinks', icon: null },
    { type: ProductType.Dessert, label: 'Desserts', icon: null },
  ];

  return (
    <>
      {/* Main Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-white shadow-md">
        {/* Top Navigation Bar */}
        <div className="border-b border-gray-100">
          <div className="max-w-7xl mx-auto px-4">
            <div className="h-16 flex items-center justify-between">
              {/* Logo */}
              <Link to="/" className="flex items-center gap-2 group">
                <div className="w-10 h-10 bg-[#E31837] rounded-full flex items-center justify-center">
                  <span className="text-white text-xl font-bold">P</span>
                </div>
                <span className="text-xl font-bold text-[#0066CC] hidden sm:block">
                  Pizza<span className="text-[#E31837]">Orders</span>
                </span>
              </Link>

              {/* Desktop Navigation */}
              <nav className="hidden md:flex items-center gap-8">
                <Link
                  to="/"
                  className="text-sm font-semibold text-gray-700 hover:text-[#0066CC] transition-colors"
                >
                  Menu
                </Link>
                {isAuthenticated && (
                  <Link
                    to="/orders"
                    className="text-sm font-semibold text-gray-700 hover:text-[#0066CC] transition-colors"
                  >
                    My Orders
                  </Link>
                )}
                {isAdmin && (
                  <Link
                    to="/admin"
                    className="text-sm font-semibold text-gray-700 hover:text-[#0066CC] transition-colors flex items-center gap-1"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                    </svg>
                    Admin
                  </Link>
                )}
              </nav>

              {/* Right Side Actions */}
              <div className="flex items-center gap-3">
                {/* Auth Section */}
                {isAuthenticated ? (
                  <div className="flex items-center gap-2">
                    <div className="hidden sm:flex items-center gap-2 px-3 py-1.5 bg-gray-50 rounded-full">
                      <div className="w-6 h-6 bg-[#0066CC] rounded-full flex items-center justify-center text-white text-xs font-bold">
                        {user?.email?.charAt(0).toUpperCase()}
                      </div>
                      <span className="text-sm font-medium text-gray-700 max-w-[120px] truncate">
                        {user?.email}
                      </span>
                    </div>
                    <button
                      onClick={logout}
                      className="p-2 text-gray-500 hover:text-[#E31837] hover:bg-red-50 rounded-full transition-all"
                      title="Logout"
                    >
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"></path>
                      </svg>
                    </button>
                  </div>
                ) : (
                  <button
                    onClick={() => setIsAuthModalOpen(true)}
                    className="flex items-center gap-2 px-4 py-2 bg-[#0066CC] text-white rounded-full font-semibold text-sm hover:bg-[#004C99] transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                    </svg>
                    <span className="hidden sm:inline">Login</span>
                  </button>
                )}

                {/* Cart Button */}
                <button
                  onClick={openCart}
                  className="relative flex items-center gap-2 px-4 py-2 bg-[#E31837] text-white rounded-full font-semibold text-sm hover:bg-[#C41230] transition-colors"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"></path>
                  </svg>
                  {itemCount > 0 && (
                    <span className="absolute -top-1 -right-1 w-5 h-5 bg-white text-[#E31837] text-xs font-bold flex items-center justify-center rounded-full">
                      {itemCount}
                    </span>
                  )}
                </button>

                {/* Mobile Menu Button */}
                <button
                  onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
                  className="md:hidden p-2 text-gray-700 hover:bg-gray-100 rounded-lg"
                >
                  <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    {isMobileMenuOpen ? (
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                    ) : (
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
                    )}
                  </svg>
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Category Navigation - Only show on menu page */}
        {isMenuPage && onTypeChange && (
          <div className="bg-gray-50 border-b border-gray-200">
            <div className="max-w-7xl mx-auto px-4">
              <div className="flex overflow-x-auto scrollbar-hide -mx-4 px-4 md:mx-0 md:px-0">
                {categories.map((category) => (
                  <button
                    key={category.type}
                    onClick={() => onTypeChange(category.type)}
                    className={`flex-shrink-0 px-6 py-3 text-sm font-semibold transition-all border-b-2 ${
                      selectedType === category.type
                        ? 'text-[#0066CC] border-[#0066CC] bg-white'
                        : 'text-gray-600 border-transparent hover:text-[#0066CC] hover:bg-white'
                    }`}
                  >
                    {category.label}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Mobile Menu Dropdown */}
        {isMobileMenuOpen && (
          <div className="md:hidden bg-white border-t border-gray-100 shadow-lg">
            <div className="px-4 py-3 space-y-2">
              <Link
                to="/"
                className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded-lg font-medium"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Menu
              </Link>
              {isAuthenticated && (
                <Link
                  to="/orders"
                  className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded-lg font-medium"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  My Orders
                </Link>
              )}
              {isAdmin && (
                <Link
                  to="/admin"
                  className="block px-4 py-2 text-gray-700 hover:bg-gray-50 rounded-lg font-medium"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  Admin Panel
                </Link>
              )}
            </div>
          </div>
        )}
      </header>

      {/* Spacer to prevent content from going under fixed header */}
      <div className={`${isMenuPage && onTypeChange ? 'h-28' : 'h-16'}`} />

      <AuthModal isOpen={isAuthModalOpen} onClose={() => setIsAuthModalOpen(false)} />
    </>
  );
};
