// frontend/src/components/common/PaymentModal.tsx
import React, { useState } from 'react';

interface PaymentModalProps {
  total: number;
  onClose: () => void;
  onSuccess: () => void;
}

export const PaymentModal: React.FC<PaymentModalProps> = ({ total, onClose, onSuccess }) => {
  const [isProcessing, setIsProcessing] = useState(false);
  const [cardNumber, setCardNumber] = useState('');
  const [expiry, setExpiry] = useState('');
  const [cvv, setCvv] = useState('');

  const handlePay = (e: React.FormEvent) => {
    e.preventDefault();
    setIsProcessing(true);

    // Simulate payment API call (mock)
    setTimeout(() => {
      setIsProcessing(false);
      onSuccess();
    }, 2500);
  };

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/80 backdrop-blur-md" onClick={onClose} />
      <div className="relative bg-white w-full max-w-md rounded-[2.5rem] overflow-hidden shadow-2xl animate-in fade-in slide-in-from-bottom-8 duration-300">
        <div className="p-8">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-2xl font-black text-gray-900">Secure Payment</h2>
            <div className="flex gap-1">
              <div className="w-8 h-5 bg-gray-100 rounded-sm"></div>
              <div className="w-8 h-5 bg-gray-100 rounded-sm"></div>
              <div className="w-8 h-5 bg-gray-100 rounded-sm"></div>
            </div>
          </div>

          <div className="bg-orange-50 p-4 rounded-2xl mb-8 flex justify-between items-center border border-orange-100">
            <span className="text-orange-900 font-bold">Total Amount</span>
            <span className="text-2xl font-black text-orange-600">${total.toFixed(2)}</span>
          </div>

          <form onSubmit={handlePay} className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">
                Card Number
              </label>
              <input
                required
                type="text"
                placeholder="1234 5678 9012 3456"
                value={cardNumber}
                onChange={(e) => setCardNumber(e.target.value)}
                className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl focus:ring-2 focus:ring-orange-500 outline-none"
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">
                  Expiry
                </label>
                <input
                  required
                  type="text"
                  placeholder="MM/YY"
                  value={expiry}
                  onChange={(e) => setExpiry(e.target.value)}
                  className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl focus:ring-2 focus:ring-orange-500 outline-none"
                />
              </div>
              <div>
                <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">
                  CVV
                </label>
                <input
                  required
                  type="password"
                  placeholder="***"
                  value={cvv}
                  onChange={(e) => setCvv(e.target.value)}
                  maxLength={3}
                  className="w-full px-4 py-3 bg-gray-50 border-none rounded-xl focus:ring-2 focus:ring-orange-500 outline-none"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={isProcessing}
              className="w-full py-4 bg-gray-900 text-white rounded-2xl font-bold shadow-xl hover:bg-black transition-all flex items-center justify-center gap-3 mt-6 disabled:opacity-50"
            >
              {isProcessing ? (
                <>
                  <svg className="animate-spin h-5 w-5 text-white" viewBox="0 0 24 24">
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                      fill="none"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                  Processing...
                </>
              ) : (
                `Pay $${total.toFixed(2)}`
              )}
            </button>
          </form>

          <p className="text-center text-xs text-gray-400 mt-6 flex items-center justify-center gap-1">
            <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
              <path
                fillRule="evenodd"
                d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z"
                clipRule="evenodd"
              ></path>
            </svg>
            SSL Secured & Encrypted (Mock Payment for Demo)
          </p>
        </div>
      </div>
    </div>
  );
};

// angular-client/src/components/payment-modal/payment-modal.component.ts
import { Component, ChangeDetectionStrategy, input, output, signal } from '@angular/core';

@Component({
  selector: 'app-payment-modal',
  templateUrl: './payment-modal.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PaymentModalComponent {
  isVisible = input.required<boolean>();
  totalAmount = input.required<number>();
  closeModal = output<void>();
  paymentSuccess = output<void>();

  isProcessing = signal(false);

  onClose() {
    if (this.isProcessing()) return;
    this.closeModal.emit();
  }

  async processPayment(event: Event) {
    event.preventDefault();
    if (this.isProcessing()) return;

    this.isProcessing.set(true);
    // Simulate API call
    await new Promise(resolve => setTimeout(resolve, 2500));
    this.isProcessing.set(false);
    this.paymentSuccess.emit();
  }
}

@if (isVisible()) {
  <div class="fixed inset-0 bg-black bg-opacity-60 z-50 flex items-center justify-center p-4" (click)="onClose()">
    <div class="bg-white rounded-xl shadow-2xl w-full max-w-md" (click)="$event.stopPropagation()">
      <form (submit)="processPayment($event)">
        <!-- Header -->
        <div class="flex justify-between items-center p-5 border-b border-gray-200">
          <h2 class="text-2xl font-bold text-gray-800">Secure Payment</h2>
          <button type="button" (click)="onClose()" [disabled]="isProcessing()" class="text-gray-500 hover:text-gray-800 disabled:opacity-50">
            <i class="fas fa-times text-2xl"></i>
          </button>
        </div>

        <!-- Body -->
        <div class="p-6 space-y-4">
          <div>
            <label for="card-number" class="block text-sm font-medium text-gray-700">Card Number</label>
            <div class="mt-1 relative rounded-md shadow-sm">
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                <i class="fa-regular fa-credit-card text-gray-400"></i>
              </div>
              <input type="text" id="card-number" class="block w-full rounded-md border-gray-300 pl-10 focus:border-red-500 focus:ring-red-500 sm:text-sm" placeholder="0000 0000 0000 0000">
            </div>
          </div>

          <div>
            <label for="card-name" class="block text-sm font-medium text-gray-700">Name on Card</label>
            <input type="text" id="card-name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm" placeholder="John M. Doe">
          </div>

          <div class="grid grid-cols-2 gap-4">
            <div>
              <label for="card-expiry" class="block text-sm font-medium text-gray-700">Expiration (MM/YY)</label>
              <input type="text" id="card-expiry" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm" placeholder="MM/YY">
            </div>
            <div>
              <label for="card-cvc" class="block text-sm font-medium text-gray-700">CVC</label>
              <input type="text" id="card-cvc" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm" placeholder="123">
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div class="p-5 bg-gray-50 border-t border-gray-200 rounded-b-xl">
          <button 
            type="submit" 
            [disabled]="isProcessing()"
            class="w-full bg-red-600 text-white font-bold py-3 rounded-lg text-lg hover:bg-red-700 transition-colors duration-300 disabled:bg-red-400 disabled:cursor-not-allowed flex items-center justify-center">
            @if (isProcessing()) {
              <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <span>Processing...</span>
            } @else {
              <span>Pay ${{ totalAmount().toFixed(2) }}</span>
            }
          </button>
        </div>
      </form>
    </div>
  </div>
}
